name: Deploy ML Service to AWS EC2

on:
  push:
    branches: [main]
    paths:
      - 'welth-ml-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            # 1. Create 2GB of Swap Space (Fake RAM)
            if [ ! -f /swapfile ]; then
              sudo fallocate -l 2G /swapfile
              sudo chmod 600 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
            fi
            
            # 2. Install Docker
            sudo apt-get update
            sudo apt-get install -y docker.io git
            sudo systemctl start docker
            sudo systemctl enable docker
            
            # 3. Clean up and download code
            rm -rf wealth-app
            ggit clone https://github.com/jkMilan/wealth-app.git
            cd wealth-app/welth-ml-service
            
            # 4. Stop old server, build and run new one
            sudo docker stop welth-ml || true
            sudo docker rm welth-ml || true
            sudo docker build -t welth-ml-image .
            sudo docker run -d --restart unless-stopped --name welth-ml -p 8000:8000 welth-ml-image